language: node_js
node_js:
    - "6"
addons:
   apt:
     sources:
        - ubuntu-toolchain-r-test
packages:
        - g++-4.8
env:
  - TEST_DIR='app/UMS'
  - CXX=g++-4.8
  
script: cd $TEST_DIR && npm install && npm test
   
